# General GitHub Repository Settings
repository:
  license: BSD-2-Clause

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: bot                                              # A unique namespace for your toolbox
  toolbox_name: Brain Observatory Toolbox                          # Name of the MATLAB toolbox                  
  author_name: John Doe                     
  author_email: johndoe@example.com         
  author_company: John Doe Inc.                     # Author's company or organization
  toolbox_summary: A MATLAB toolbox for interacting with the Allen Brain Observatory
  toolbox_description: |
    A MATLAB toolbox for accessing and using the neural recording 
    public datasets from the Allen Brain Observatory
  dependencies:                                     # Required MATLAB products
    - MATLAB

# Publishing options
codecov:
  badge_token: Z2L1HGYAPV

fileexchange:
  fex_url: https://se.mathworks.com/matlabcentral/fileexchange/90900-brain-observatory-toolbox
