name: Test code

on:
  push:
    branches: main
    paths-ignore:
      - '*md'
      - '.github/**'
      - 'config.yaml'


  pull_request:
    branches: main
    paths-ignore:
      - '*md'
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    if: github.run_number > 1
    name: Analyse and test code
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      matlab_use_cache: true
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
